version: "3.8"

services:
  # ==========================
  # Servicio para DESARROLLO
  # ==========================
  dev:
    image: mi-app-simple # Usa la imagen de desarrollo pre-construida
    ports:
      - "5173:5173"
    volumes:
      # Montamos explícitamente solo lo que necesitamos para el hot-reload.
      # Esto evita conflictos con la carpeta node_modules del contenedor.
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./vite.config.ts:/app/vite.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.app.json:/app/tsconfig.app.json
    env_file:
      - ${ENV_FILE:-.env.local}
    profiles:
      - development # Perfil para desarrollo

  # ==========================
  # Servicio para PRODUCCIÓN
  # ==========================
  prod:
    image: mi-app-prod # Usa la imagen de producción pre-construida
    ports:
      - "8080:80" # Mapeamos el puerto 80 del contenedor al 8080 de tu PC
    profiles:
      - production # Perfil para producción
